on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install & CI
        run: |
          pnpm install --frozen-lockfile
          pnpm run ci

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --no-git-checks
